### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mikeymike** [php-school/workshop-manager#1]
- [x] Read `workshop.json` from repo master not local copy
- [x] Verbose options for Install command 
- [x] Handle offline system... revert to local file ? user should still be able to list installed workshops.
- [x] Exception handling on installer :cop: 
  - [x] FileSystem exceptions
  - [x] Composer exceptions
  - [x] Downloader FileExists exception (when zip exists and temp cant clean)
- [x] Symlink process :exclamation: 
  - [x] On install
- [x] Tests :sweat_smile: 
  - [x] Commands
  - [x] Downloader
  - [x] Installer
  - [x] ManagerState
  - [x] Uninstaller
  - [x] Repository
  - [x] Entity
  - [x] the rest...
- [x] Fix list command conflict
  - [x] Maybe switch out Symfony console? 
- [x] Wrap it up in a phar
- [x] Self update command
- [x] Docs
  - [x] Installation
  - [x] Submitting a Workshop

**Comment by AydinHassan** [comment]
Done!
